version: "3.5"

services:
  tumo-boot-ui:
    image: tumo-boot-ui
    build:
      context: .
    restart: always
    container_name: tumo-boot-ui
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 8091:80
