version: "3.5"

services:
  tumo-boot-admin:
    build:
      context: .
    restart: always
    container_name: tumo-boot-admin
    image: tumo-boot-admin
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 8091:80
